import type { ExerciseCatalogMuscleGroupId } from "../exercise-selection-preferences";

export const exerciseCatalogBodyMapAsset = {
  height: 452,
  width: 695,
} as const;

export type ExerciseCatalogBodyMapHotspot = {
  height: number;
  id: string;
  label: string;
  left: number;
  muscleGroupId: ExerciseCatalogMuscleGroupId;
  top: number;
  view: "back" | "front";
  width: number;
};

export type ExerciseCatalogBodyMapSelectionOverlay = {
  height: number;
  id: string;
  left: number;
  muscleGroupId: ExerciseCatalogMuscleGroupId;
  radius: string;
  top: number;
  width: number;
};

export const exerciseCatalogBodyMapHotspots = [
  {
    height: 66,
    id: "front-chest",
    label: "front chest",
    left: 102,
    muscleGroupId: "chest",
    top: 93,
    view: "front",
    width: 152,
  },
  {
    height: 54,
    id: "front-left-shoulder",
    label: "front left shoulder",
    left: 78,
    muscleGroupId: "shoulders",
    top: 96,
    view: "front",
    width: 56,
  },
  {
    height: 54,
    id: "front-right-shoulder",
    label: "front right shoulder",
    left: 225,
    muscleGroupId: "shoulders",
    top: 96,
    view: "front",
    width: 56,
  },
  {
    height: 54,
    id: "back-left-shoulder",
    label: "back left shoulder",
    left: 427,
    muscleGroupId: "shoulders",
    top: 97,
    view: "back",
    width: 62,
  },
  {
    height: 54,
    id: "back-right-shoulder",
    label: "back right shoulder",
    left: 558,
    muscleGroupId: "shoulders",
    top: 97,
    view: "back",
    width: 62,
  },
  {
    height: 134,
    id: "front-left-biceps",
    label: "front left biceps",
    left: 61,
    muscleGroupId: "biceps",
    top: 146,
    view: "front",
    width: 55,
  },
  {
    height: 134,
    id: "front-right-biceps",
    label: "front right biceps",
    left: 239,
    muscleGroupId: "biceps",
    top: 146,
    view: "front",
    width: 55,
  },
  {
    height: 132,
    id: "back-left-triceps",
    label: "back left triceps",
    left: 391,
    muscleGroupId: "triceps",
    top: 146,
    view: "back",
    width: 56,
  },
  {
    height: 132,
    id: "back-right-triceps",
    label: "back right triceps",
    left: 603,
    muscleGroupId: "triceps",
    top: 146,
    view: "back",
    width: 56,
  },
  {
    height: 94,
    id: "front-left-forearm",
    label: "front left forearm",
    left: 34,
    muscleGroupId: "forearms",
    top: 248,
    view: "front",
    width: 55,
  },
  {
    height: 94,
    id: "front-right-forearm",
    label: "front right forearm",
    left: 268,
    muscleGroupId: "forearms",
    top: 248,
    view: "front",
    width: 55,
  },
  {
    height: 132,
    id: "front-abs",
    label: "front abs",
    left: 132,
    muscleGroupId: "abs",
    top: 160,
    view: "front",
    width: 91,
  },
  {
    height: 172,
    id: "back-lats",
    label: "back and lats",
    left: 468,
    muscleGroupId: "back",
    top: 105,
    view: "back",
    width: 112,
  },
  {
    height: 94,
    id: "back-glutes",
    label: "back glutes",
    left: 466,
    muscleGroupId: "glutes",
    top: 270,
    view: "back",
    width: 118,
  },
  {
    height: 126,
    id: "front-left-quad",
    label: "front left quadriceps",
    left: 105,
    muscleGroupId: "quadriceps",
    top: 292,
    view: "front",
    width: 61,
  },
  {
    height: 126,
    id: "front-right-quad",
    label: "front right quadriceps",
    left: 188,
    muscleGroupId: "quadriceps",
    top: 292,
    view: "front",
    width: 61,
  },
  {
    height: 124,
    id: "back-left-hamstring",
    label: "back left hamstrings",
    left: 443,
    muscleGroupId: "hamstrings",
    top: 292,
    view: "back",
    width: 66,
  },
  {
    height: 124,
    id: "back-right-hamstring",
    label: "back right hamstrings",
    left: 544,
    muscleGroupId: "hamstrings",
    top: 292,
    view: "back",
    width: 66,
  },
  {
    height: 62,
    id: "front-left-calf",
    label: "front left calf",
    left: 112,
    muscleGroupId: "calves",
    top: 388,
    view: "front",
    width: 50,
  },
  {
    height: 62,
    id: "front-right-calf",
    label: "front right calf",
    left: 194,
    muscleGroupId: "calves",
    top: 388,
    view: "front",
    width: 50,
  },
] as const satisfies ReadonlyArray<ExerciseCatalogBodyMapHotspot>;

export const exerciseCatalogBodyMapSelectionOverlays = [
  {
    height: 46,
    id: "front-left-shoulder-selected",
    left: 82,
    muscleGroupId: "shoulders",
    radius: "50%",
    top: 101,
    width: 50,
  },
  {
    height: 46,
    id: "front-right-shoulder-selected",
    left: 226,
    muscleGroupId: "shoulders",
    radius: "50%",
    top: 101,
    width: 50,
  },
  {
    height: 112,
    id: "front-left-biceps-selected",
    left: 71,
    muscleGroupId: "biceps",
    radius: "999px",
    top: 158,
    width: 34,
  },
  {
    height: 112,
    id: "front-right-biceps-selected",
    left: 251,
    muscleGroupId: "biceps",
    radius: "999px",
    top: 158,
    width: 34,
  },
  {
    height: 112,
    id: "back-left-triceps-selected",
    left: 403,
    muscleGroupId: "triceps",
    radius: "999px",
    top: 158,
    width: 34,
  },
  {
    height: 112,
    id: "back-right-triceps-selected",
    left: 615,
    muscleGroupId: "triceps",
    radius: "999px",
    top: 158,
    width: 34,
  },
  {
    height: 110,
    id: "front-abs-selected",
    left: 145,
    muscleGroupId: "abs",
    radius: "44%",
    top: 172,
    width: 66,
  },
  {
    height: 146,
    id: "back-lats-selected",
    left: 476,
    muscleGroupId: "back",
    radius: "36%",
    top: 116,
    width: 96,
  },
  {
    height: 78,
    id: "back-glutes-selected",
    left: 474,
    muscleGroupId: "glutes",
    radius: "40%",
    top: 280,
    width: 102,
  },
  {
    height: 118,
    id: "front-quads-selected",
    left: 105,
    muscleGroupId: "quadriceps",
    radius: "42%",
    top: 300,
    width: 144,
  },
  {
    height: 116,
    id: "back-hamstrings-selected",
    left: 444,
    muscleGroupId: "hamstrings",
    radius: "42%",
    top: 300,
    width: 166,
  },
  {
    height: 78,
    id: "front-forearms-selected",
    left: 34,
    muscleGroupId: "forearms",
    radius: "999px",
    top: 258,
    width: 289,
  },
  {
    height: 58,
    id: "front-calves-selected",
    left: 110,
    muscleGroupId: "calves",
    radius: "999px",
    top: 390,
    width: 136,
  },
] as const satisfies ReadonlyArray<ExerciseCatalogBodyMapSelectionOverlay>;
