export type ExerciseCatalogMuscleGroupId =
  | "abs"
  | "back"
  | "biceps"
  | "calves"
  | "chest"
  | "forearms"
  | "glutes"
  | "hamstrings"
  | "quadriceps"
  | "shoulders"
  | "triceps";

export type MovementPatternId =
  | "horizontal_push"
  | "horizontal_pull"
  | "vertical_push"
  | "vertical_pull"
  | "elbow_flexion"
  | "elbow_extension"
  | "quad_dominant"
  | "hip_hamstring_dominant"
  | "calves_accessories"
  | "core";

export type ExerciseRoleId = "compound" | "isolation";

export const compoundCapableMovementPatterns = [
  "horizontal_push",
  "horizontal_pull",
  "vertical_push",
  "vertical_pull",
  "quad_dominant",
  "hip_hamstring_dominant",
] as const satisfies ReadonlyArray<MovementPatternId>;

export type CompoundCapableMovementPatternId = (typeof compoundCapableMovementPatterns)[number];

export type ExerciseCatalogExercise = {
  catalogMuscleGroup: ExerciseCatalogMuscleGroupId;
  id: string;
  movementPattern: MovementPatternId;
  name: string;
  primaryMuscleGroups: readonly [ExerciseCatalogMuscleGroupId, ...ExerciseCatalogMuscleGroupId[]];
  role: ExerciseRoleId;
  secondaryMuscleGroups: ReadonlyArray<ExerciseCatalogMuscleGroupId>;
};

type ExerciseCatalogMuscleGroup = {
  exercises: ReadonlyArray<string>;
  id: ExerciseCatalogMuscleGroupId;
  title: string;
};

const exerciseCatalogMuscleGroupDefinitions = [
  { id: "chest", title: "Chest" },
  { id: "back", title: "Back" },
  { id: "shoulders", title: "Shoulders" },
  { id: "quadriceps", title: "Quadriceps" },
  { id: "hamstrings", title: "Hamstrings" },
  { id: "biceps", title: "Biceps" },
  { id: "triceps", title: "Triceps" },
  { id: "forearms", title: "Forearms" },
  { id: "abs", title: "Abs" },
  { id: "glutes", title: "Glutes" },
  { id: "calves", title: "Calves" },
] as const satisfies ReadonlyArray<{
  id: ExerciseCatalogMuscleGroupId;
  title: string;
}>;

const legacyConcreteExerciseIdById: Record<string, string> = {
  "barbell-dumbbell-or-machine-rear-delt-rows-raises-or-flyes": "dumbbell-rear-delt-flyes",
  "barbell-dumbbell-or-machine-shrugs": "barbell-shrugs",
  "barbell-dumbbell-or-machine-upright-rows": "barbell-upright-rows",
  "barbell-or-dumbbell-front-squats": "barbell-front-squats",
  "barbell-or-dumbbell-lunges": "barbell-lunges",
  "barbell-or-dumbbell-preacher-curls": "barbell-preacher-curls",
  "barbell-or-dumbbell-romanian-deadlifts": "barbell-romanian-deadlifts",
  "barbell-or-dumbbell-split-squats": "barbell-split-squats",
  "barbell-or-dumbbell-squats": "barbell-squats",
  "barbell-or-dumbbell-step-ups": "barbell-step-ups",
  "barbell-or-dumbbell-straight-leg-deadlifts": "barbell-straight-leg-deadlifts",
  "barbell-or-dumbbell-sumo-deadlifts": "barbell-sumo-deadlifts",
  "bent-over-barbell-or-dumbbell-rows": "bent-over-barbell-rows",
  "chest-supported-barbell-or-dumbbell-rows": "chest-supported-barbell-rows",
  "decline-barbell-or-dumbbell-bench-press": "decline-barbell-bench-press",
  "dumbbell-cable-or-machine-front-raises": "dumbbell-front-raises",
  "dumbbell-cable-or-machine-lateral-raises": "dumbbell-lateral-raises",
  "flat-barbell-or-dumbbell-bench-press": "flat-barbell-bench-press",
  "incline-barbell-or-dumbbell-bench-press": "incline-barbell-bench-press",
  "laying-barbell-or-dumbbell-triceps-extensions": "laying-barbell-triceps-extensions",
  "overhead-barbell-or-dumbbell-triceps-extensions": "overhead-barbell-triceps-extensions",
  "seated-overhead-barbell-or-dumbbell-press": "seated-overhead-barbell-press",
  "standing-barbell-or-dumbbell-curls": "standing-barbell-curls",
  "standing-overhead-barbell-or-dumbbell-press": "standing-overhead-barbell-press",
};

// Exercise names are based on AWorkoutRoutine's muscle-group exercise list.
// Movement pattern, role, and secondary muscles are derived planning metadata.
export const exerciseCatalogExercises = [
  {
    catalogMuscleGroup: "chest",
    id: "flat-barbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Flat Barbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "flat-dumbbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Flat Dumbbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "incline-barbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Incline Barbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "incline-dumbbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Incline Dumbbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "decline-barbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Decline Barbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "decline-dumbbell-bench-press",
    movementPattern: "horizontal_push",
    name: "Decline Dumbbell Bench Press",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "flat-chest-press-machine",
    movementPattern: "horizontal_push",
    name: "Flat Chest Press Machine",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "incline-chest-press-machine",
    movementPattern: "horizontal_push",
    name: "Incline Chest Press Machine",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "decline-chest-press-machine",
    movementPattern: "horizontal_push",
    name: "Decline Chest Press Machine",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["shoulders", "triceps"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "dips-parallel-bars-slight-forward-lean",
    movementPattern: "horizontal_push",
    name: "Dips (Parallel Bars, Slight Forward Lean)",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["triceps", "shoulders"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "push-ups",
    movementPattern: "horizontal_push",
    name: "Push-Ups",
    primaryMuscleGroups: ["chest"],
    role: "compound",
    secondaryMuscleGroups: ["triceps", "shoulders"],
  },
  {
    catalogMuscleGroup: "chest",
    id: "flat-dumbbell-flyes",
    movementPattern: "horizontal_push",
    name: "Flat Dumbbell Flyes",
    primaryMuscleGroups: ["chest"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "chest",
    id: "incline-dumbbell-flyes",
    movementPattern: "horizontal_push",
    name: "Incline Dumbbell Flyes",
    primaryMuscleGroups: ["chest"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "chest",
    id: "decline-dumbbell-flyes",
    movementPattern: "horizontal_push",
    name: "Decline Dumbbell Flyes",
    primaryMuscleGroups: ["chest"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "chest",
    id: "pec-deck-machine",
    movementPattern: "horizontal_push",
    name: "Pec Deck Machine",
    primaryMuscleGroups: ["chest"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "chest",
    id: "cable-crossovers-cable-flyes",
    movementPattern: "horizontal_push",
    name: "Cable Crossovers/Cable Flyes",
    primaryMuscleGroups: ["chest"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "back",
    id: "pull-ups",
    movementPattern: "vertical_pull",
    name: "Pull-Ups",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "chin-ups",
    movementPattern: "vertical_pull",
    name: "Chin-Ups",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "lat-pull-downs",
    movementPattern: "vertical_pull",
    name: "Lat Pull-Downs",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "neutral-grip-pulldown",
    movementPattern: "vertical_pull",
    name: "Neutral-Grip Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "assisted-pull-up",
    movementPattern: "vertical_pull",
    name: "Assisted Pull-Up",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "wide-grip-lat-pulldown",
    movementPattern: "vertical_pull",
    name: "Wide-Grip Lat Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "close-grip-lat-pulldown",
    movementPattern: "vertical_pull",
    name: "Close-Grip Lat Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "reverse-grip-lat-pulldown",
    movementPattern: "vertical_pull",
    name: "Reverse-Grip Lat Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "close-neutral-grip-pulldown",
    movementPattern: "vertical_pull",
    name: "Close Neutral-Grip Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "medium-grip-lat-pulldown",
    movementPattern: "vertical_pull",
    name: "Medium-Grip Lat Pulldown",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "bent-over-barbell-rows",
    movementPattern: "horizontal_pull",
    name: "Bent Over Barbell Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "bent-over-dumbbell-rows",
    movementPattern: "horizontal_pull",
    name: "Bent Over Dumbbell Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "t-bar-rows",
    movementPattern: "horizontal_pull",
    name: "T-Bar Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "seated-cable-rows",
    movementPattern: "horizontal_pull",
    name: "Seated Cable Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "chest-supported-barbell-rows",
    movementPattern: "horizontal_pull",
    name: "Chest Supported Barbell Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "chest-supported-dumbbell-rows",
    movementPattern: "horizontal_pull",
    name: "Chest Supported Dumbbell Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "chest-supported-machine-rows",
    movementPattern: "horizontal_pull",
    name: "Chest Supported Machine Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "inverted-rows",
    movementPattern: "horizontal_pull",
    name: "Inverted Rows",
    primaryMuscleGroups: ["back"],
    role: "compound",
    secondaryMuscleGroups: ["biceps", "forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "barbell-shrugs",
    movementPattern: "calves_accessories",
    name: "Barbell Shrugs",
    primaryMuscleGroups: ["back"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "dumbbell-shrugs",
    movementPattern: "calves_accessories",
    name: "Dumbbell Shrugs",
    primaryMuscleGroups: ["back"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "back",
    id: "machine-shrugs",
    movementPattern: "calves_accessories",
    name: "Machine Shrugs",
    primaryMuscleGroups: ["back"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "seated-overhead-barbell-press",
    movementPattern: "vertical_push",
    name: "Seated Overhead Barbell Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "seated-overhead-dumbbell-press",
    movementPattern: "vertical_push",
    name: "Seated Overhead Dumbbell Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "standing-overhead-barbell-press",
    movementPattern: "vertical_push",
    name: "Standing Overhead Barbell Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "standing-overhead-dumbbell-press",
    movementPattern: "vertical_push",
    name: "Standing Overhead Dumbbell Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "overhead-machine-press",
    movementPattern: "vertical_push",
    name: "Overhead Machine Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "arnold-press",
    movementPattern: "vertical_push",
    name: "Arnold Press",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["triceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "barbell-upright-rows",
    movementPattern: "calves_accessories",
    name: "Barbell Upright Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["back", "biceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-upright-rows",
    movementPattern: "calves_accessories",
    name: "Dumbbell Upright Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["back", "biceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-upright-rows",
    movementPattern: "calves_accessories",
    name: "Machine Upright Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "compound",
    secondaryMuscleGroups: ["back", "biceps"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-lateral-raises",
    movementPattern: "vertical_push",
    name: "Dumbbell Lateral Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "cable-lateral-raises",
    movementPattern: "vertical_push",
    name: "Cable Lateral Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-lateral-raises",
    movementPattern: "vertical_push",
    name: "Machine Lateral Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-front-raises",
    movementPattern: "vertical_push",
    name: "Dumbbell Front Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "cable-front-raises",
    movementPattern: "vertical_push",
    name: "Cable Front Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-front-raises",
    movementPattern: "vertical_push",
    name: "Machine Front Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "barbell-rear-delt-rows",
    movementPattern: "horizontal_pull",
    name: "Barbell Rear Delt Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-rear-delt-rows",
    movementPattern: "horizontal_pull",
    name: "Dumbbell Rear Delt Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-rear-delt-rows",
    movementPattern: "horizontal_pull",
    name: "Machine Rear Delt Rows",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-rear-delt-raises",
    movementPattern: "horizontal_pull",
    name: "Dumbbell Rear Delt Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-rear-delt-raises",
    movementPattern: "horizontal_pull",
    name: "Machine Rear Delt Raises",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "dumbbell-rear-delt-flyes",
    movementPattern: "horizontal_pull",
    name: "Dumbbell Rear Delt Flyes",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "shoulders",
    id: "machine-rear-delt-flyes",
    movementPattern: "horizontal_pull",
    name: "Machine Rear Delt Flyes",
    primaryMuscleGroups: ["shoulders"],
    role: "isolation",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "barbell-squats",
    movementPattern: "quad_dominant",
    name: "Barbell Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "dumbbell-squats",
    movementPattern: "quad_dominant",
    name: "Dumbbell Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "barbell-front-squats",
    movementPattern: "quad_dominant",
    name: "Barbell Front Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "dumbbell-front-squats",
    movementPattern: "quad_dominant",
    name: "Dumbbell Front Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "barbell-split-squats",
    movementPattern: "quad_dominant",
    name: "Barbell Split Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "dumbbell-split-squats",
    movementPattern: "quad_dominant",
    name: "Dumbbell Split Squats",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "barbell-lunges",
    movementPattern: "quad_dominant",
    name: "Barbell Lunges",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "dumbbell-lunges",
    movementPattern: "quad_dominant",
    name: "Dumbbell Lunges",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "barbell-step-ups",
    movementPattern: "quad_dominant",
    name: "Barbell Step-Ups",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "dumbbell-step-ups",
    movementPattern: "quad_dominant",
    name: "Dumbbell Step-Ups",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "leg-press",
    movementPattern: "quad_dominant",
    name: "Leg Press",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "single-leg-press",
    movementPattern: "quad_dominant",
    name: "Single Leg Press",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "machine-squat-hack-squat",
    movementPattern: "quad_dominant",
    name: "Machine Squat/Hack Squat",
    primaryMuscleGroups: ["quadriceps"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "hamstrings"],
  },
  {
    catalogMuscleGroup: "quadriceps",
    id: "leg-extensions",
    movementPattern: "quad_dominant",
    name: "Leg Extensions",
    primaryMuscleGroups: ["quadriceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "barbell-romanian-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Barbell Romanian Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "dumbbell-romanian-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Dumbbell Romanian Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "barbell-straight-leg-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Barbell Straight Leg Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "dumbbell-straight-leg-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Dumbbell Straight Leg Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "barbell-sumo-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Barbell Sumo Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "quadriceps", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "dumbbell-sumo-deadlifts",
    movementPattern: "hip_hamstring_dominant",
    name: "Dumbbell Sumo Deadlifts",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back", "quadriceps", "forearms"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "glute-ham-raises",
    movementPattern: "hip_hamstring_dominant",
    name: "Glute-Ham Raises",
    primaryMuscleGroups: ["hamstrings"],
    role: "compound",
    secondaryMuscleGroups: ["glutes"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "hyperextensions",
    movementPattern: "hip_hamstring_dominant",
    name: "Hyperextensions",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: ["back"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "cable-pull-throughs",
    movementPattern: "hip_hamstring_dominant",
    name: "Cable Pull-Throughs",
    primaryMuscleGroups: ["hamstrings", "glutes"],
    role: "compound",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "good-mornings",
    movementPattern: "hip_hamstring_dominant",
    name: "Good-Mornings",
    primaryMuscleGroups: ["hamstrings"],
    role: "compound",
    secondaryMuscleGroups: ["glutes", "back"],
  },
  {
    catalogMuscleGroup: "hamstrings",
    id: "leg-curls",
    movementPattern: "hip_hamstring_dominant",
    name: "Leg Curls",
    primaryMuscleGroups: ["hamstrings"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "calves",
    id: "standing-calf-raises",
    movementPattern: "calves_accessories",
    name: "Standing Calf Raises",
    primaryMuscleGroups: ["calves"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "standing-barbell-curls",
    movementPattern: "elbow_flexion",
    name: "Standing Barbell Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "standing-dumbbell-curls",
    movementPattern: "elbow_flexion",
    name: "Standing Dumbbell Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "barbell-preacher-curls",
    movementPattern: "elbow_flexion",
    name: "Barbell Preacher Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "dumbbell-preacher-curls",
    movementPattern: "elbow_flexion",
    name: "Dumbbell Preacher Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "seated-dumbbell-curls",
    movementPattern: "elbow_flexion",
    name: "Seated Dumbbell Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "incline-dumbbell-curls",
    movementPattern: "elbow_flexion",
    name: "Incline Dumbbell Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "hammer-curls",
    movementPattern: "elbow_flexion",
    name: "Hammer Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "concentration-curls",
    movementPattern: "elbow_flexion",
    name: "Concentration Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "cable-curls",
    movementPattern: "elbow_flexion",
    name: "Cable Curls",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "biceps",
    id: "biceps-curl-machine",
    movementPattern: "elbow_flexion",
    name: "Biceps Curl Machine",
    primaryMuscleGroups: ["biceps"],
    role: "isolation",
    secondaryMuscleGroups: ["forearms"],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "dips-elbows-close-no-forward-lean",
    movementPattern: "horizontal_push",
    name: "Dips (Elbows Close, No Forward Lean)",
    primaryMuscleGroups: ["triceps"],
    role: "compound",
    secondaryMuscleGroups: ["chest", "shoulders"],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "flat-close-grip-bench-press",
    movementPattern: "horizontal_push",
    name: "Flat Close Grip Bench Press",
    primaryMuscleGroups: ["triceps"],
    role: "compound",
    secondaryMuscleGroups: ["chest", "shoulders"],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "decline-close-grip-bench-press",
    movementPattern: "horizontal_push",
    name: "Decline Close Grip Bench Press",
    primaryMuscleGroups: ["triceps"],
    role: "compound",
    secondaryMuscleGroups: ["chest", "shoulders"],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "close-grip-push-ups",
    movementPattern: "horizontal_push",
    name: "Close Grip Push-Ups",
    primaryMuscleGroups: ["triceps"],
    role: "compound",
    secondaryMuscleGroups: ["chest", "shoulders"],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "laying-barbell-triceps-extensions",
    movementPattern: "elbow_extension",
    name: "Laying Barbell Triceps Extensions",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "laying-dumbbell-triceps-extensions",
    movementPattern: "elbow_extension",
    name: "Laying Dumbbell Triceps Extensions",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "skull-crushers",
    movementPattern: "elbow_extension",
    name: "Skull Crushers",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "overhead-barbell-triceps-extensions",
    movementPattern: "elbow_extension",
    name: "Overhead Barbell Triceps Extensions",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "overhead-dumbbell-triceps-extensions",
    movementPattern: "elbow_extension",
    name: "Overhead Dumbbell Triceps Extensions",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "cable-press-downs",
    movementPattern: "elbow_extension",
    name: "Cable Press-Downs",
    primaryMuscleGroups: ["triceps"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "triceps",
    id: "bench-dips",
    movementPattern: "horizontal_push",
    name: "Bench Dips",
    primaryMuscleGroups: ["triceps"],
    role: "compound",
    secondaryMuscleGroups: ["chest", "shoulders"],
  },
  {
    catalogMuscleGroup: "abs",
    id: "cable-crunches",
    movementPattern: "core",
    name: "Cable Crunches",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "hanging-leg-raises",
    movementPattern: "core",
    name: "Hanging Leg Raises",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "planks",
    movementPattern: "core",
    name: "Planks",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "ab-wheel-rollouts",
    movementPattern: "core",
    name: "Ab Wheel Rollouts",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: ["shoulders"],
  },
  {
    catalogMuscleGroup: "abs",
    id: "dead-bugs",
    movementPattern: "core",
    name: "Dead Bugs",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "reverse-crunches",
    movementPattern: "core",
    name: "Reverse Crunches",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "side-planks",
    movementPattern: "core",
    name: "Side Planks",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
  {
    catalogMuscleGroup: "abs",
    id: "hollow-holds",
    movementPattern: "core",
    name: "Hollow Holds",
    primaryMuscleGroups: ["abs"],
    role: "isolation",
    secondaryMuscleGroups: [],
  },
] as const satisfies ReadonlyArray<ExerciseCatalogExercise>;

export const exerciseCatalogMuscleGroups = exerciseCatalogMuscleGroupDefinitions.map(
  (muscleGroup) => ({
    ...muscleGroup,
    exercises: exerciseCatalogExercises
      .filter((exercise) => exercise.catalogMuscleGroup === muscleGroup.id)
      .map((exercise) => exercise.name),
  }),
) satisfies ReadonlyArray<ExerciseCatalogMuscleGroup>;

export function getExerciseCatalogExercisesByMovementPattern(
  movementPattern: MovementPatternId,
): ReadonlyArray<ExerciseCatalogExercise> {
  return exerciseCatalogExercises.filter(
    (exercise) => exercise.movementPattern === movementPattern,
  );
}

export function getExerciseCatalogExercise(
  exerciseId: string,
): ExerciseCatalogExercise | undefined {
  return exerciseCatalogExercises.find(
    (exercise) => exercise.id === getConcreteExerciseCatalogExerciseId(exerciseId),
  );
}

export function getConcreteExerciseCatalogExerciseId(exerciseId: string): string {
  return legacyConcreteExerciseIdById[exerciseId] ?? exerciseId;
}

export function isCompoundCapableMovementPattern(
  movementPattern: unknown,
): movementPattern is CompoundCapableMovementPatternId {
  return compoundCapableMovementPatterns.some((pattern) => pattern === movementPattern);
}

export function isMainCompoundEligible<
  T extends Pick<ExerciseCatalogExercise, "movementPattern" | "role">,
>(
  exercise: T,
): exercise is T & {
  movementPattern: CompoundCapableMovementPatternId;
  role: "compound";
} {
  return exercise.role === "compound" && isCompoundCapableMovementPattern(exercise.movementPattern);
}
